<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-admin.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
	korea translation made by minwook shin
	https://github.com/minwook-shin

*/


	return array(
		'active_widgets_explanation' => '현재 사용중인 위젯:',
		'add_category_button' => '카테고리 추가',
		'add_field_button' => '칸 추가',
		'add_link_button' => '링크 추가',
		'add_link_link' => ' - ^1링크 추가^2',
		'add_new_field' => '새 빈칸 추가',
		'add_new_title' => '새 타이틀 추가',
		'add_page_button' => '페이지 추가',
		'add_title_button' => '타이틀 추가',
		'add_widget_button' => '위젯 추가',
		'add_widget_link' => ' - ^1위젯 추가^2',
		'admin_title' => '관리 센터',
		'approve_user_popup' => '허용 유저',
		'after_footer' => '바닥 글에 링크 한 후',
		'after_main_menu' => '상단의 탭 후',
		'after_x_tab' => '"^"탭 후',
		'after_x' => '"^"후',
		'moderate_title' => '모더레이터',
		'basic_editor' => '기본 편집기',
		'before_main_menu' => '상단의 탭 하기 전에',
		'blobs_directory_error' => '이 디렉토리는 ^ QA_BLOBS_DIRECTORY로 정의하고 웹 서버에 쓰기 가능 권한이 없습니다 .',
		'blobs_move_complete' => '업로드된 이미지와 문서의 마이그레이션이 완료되었습니다.',
		'blobs_move_moved' => '마이그레이션 ^2 의 ^1 이미지와 문서가 업로드되었습니다.',
		'blobs_stop' => '마이그레이션 중지',
		'blobs_to_db' => '데이터베이스에 blobs(번역 불가)',
		'blobs_to_db_note' => '- 데이터베이스에 디스크파일에서의 모든 이미지와 문서를 업로드하고 마이그레이션합니다.',
		'blobs_to_disk' => '디스크에 blobs(번역 불가)',
		'blobs_to_disk_note' => '- 디스크 파일에 데이터베이스에서의 모든 이미지 및 문서를 업로드하고 마이그레이션합니다.',
		'block_button' => '제한',
		'block_ips_note' => '범위에 대해 하이픈을 사용하거나 임의의 숫자*와 일치하도록 합니다. 예시: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_user_popup' => '제한된 유저',
		'block_words_note' => '모든 문자와 일치하도록 * 를 사용합니다. 예시: 우분투 (오직 우분투만 인식될것) , 우분투* (우분투설치 혹은 우분투오류도 인식됨) , *분투 (주분투,루분투등도 인식됨).',
		'cancel_mailing_button' => '메일링 취소',
		'categories_introduction' => '카테고리 를 시작 합니다., \'카테고리 추가\' 버튼을 클릭.',
		'categories_not_shown' => '카테고리가 있는 몇 가지 질문이 표시되지 않습니다 ',
		'categories_title' => '카테고리',
		'categories' => '카테고리',
		'category_add_sub' => '하위 카테고리 추가',
		'category_added' => '카테고리 추가됨',
		'category_already_used' => '이 카테고리는 이미 사용되고 있음',
		'category_default_slug' => '카테고리-^',
		'category_description' => '부가적인 카테고리 설명:',
		'category_max_depth_x' => '^ 레벨보다 상위 카테고리로 가는것의 일부 옵션은 아마도 숨겨져 있을 것입니다. .',
		'category_move_parent' => '다른 상위로 이동',
		'category_name_first' => '첫번째 카테고리의 이름:',
		'category_name' => '카테고리 이름:',
		'category_no_add_subs_x' => '이 아래로 이미 ^ 레벨이기 때문에 이 카테고리에 하위 카테고리를 가질 수 없습니다.',
		'category_no_delete_subs' => '하위 카테고리를 가지고 있기 때문에 이 카테고리는 삭제할 수 없습니다.',
		'category_no_sub_error' => '^q question/s 이 카테고리는 하위 카테고리를 가지고 있지 않습니다 - ^1하위 카테고리 설정^2',
		'category_no_sub_to' => '^ 같이 하위 카테고리가 없는 질문으로 이동:',
		'category_no_subs' => '없음',
		'category_none_error' => '^q question/s 현재 카테고리가 없습니다 - ^1카테고리 설정^2',
		'category_none_to' => '카테고리가 없는 곳으로 질문 이동:',
		'category_parent' => '상위 디렉토리:',
		'category_saved' => '카테고리 저장됨',
		'category_slug' => '카테고리 대용 - URL:',
		'category_subs' => '하위-카테고리:',
		'category_top_level' => '상위가 없음 (가장 높은 레벨)',
		'characters' => '글자',
		'check_language_suffix' => ' - ^1언어파일 체크^2',
		'click_name_edit' => '커스텀 페이지 또는 링크:',
		'database_cleanup' => '데이터베이스 정리 작업',
		'delete_category_reassign' => '이 카테고리를 삭제 하고 해당 질문에 재할당:',
		'delete_category' => '이 카테고리 삭제',
		'delete_field' => '이 칸 삭제',
		'delete_hidden_complete' => '상위 없는 숨겨진 모든 게시물이 삭제 되었습니다',
		'delete_hidden_note' => ' - 상위 없는 모든 숨겨진 질문, 답변 그리고 댓글',
		'delete_hidden' => '숨긴 게시물 삭제',
		'delete_link' => '이 링크 삭제',
		'delete_page' => '이 페이지 삭제',
		'delete_stop' => '삭제 작업 멈춤',
		'delete_title' => '이 타이틀 삭제',
		'delete_widget_position' => '이 위치에서 이 위젯을 삭제',
		'edit_custom_page' => '커스텀 페이지 수정',
		'edit_field' => ' - ^1칸 수정^2',
		'edit_link' => ' - ^1링크 수정^2',
		'edit_page' => ' - ^1페이지 수정^2',
		'edit_title' => ' - ^1타이틀 수정^2',
		'emails_per_minute' => '분당 이메일',
		'emails_title' => '이메일',
		'feed_link_example' => '피드 예시',
		'feed_link' => '피드',
		'feeds_title' => 'RSS피드',
		'field_link_url' => '링크된 URL',
		'field_multi_line' => '여러 줄의 텍스트',
		'field_name' => '이름 칸:',
		'field_single_line' => '한줄의 텍스트',
		'field_type' => '컨텐츠 유형:',
		'first' => '첫번째',
		'flagged_title' => '신고',
		'form_security_expired' => '양식 보안 코드가 만료됨 - 다시 시도해주십시오',
		'from_anon' => '익명인으로 부터:',
		'from_users' => '유저로 부터:',
		'general_title' => '일반',
		'hidden_answers_deleted' => '상위 없이 ^1 숨겨진 답변 ^2 삭제...',
		'hidden_comments_deleted' => '삭제 ^2 숨겨진 코멘트 ^1...',
		'hidden_questions_deleted' => '상위 없이 ^1 숨겨진질문 ^2 삭제 ...',
		'hotness_factors' => '이슈되지 않은 질문의 상대적 중요성:',
		'hidden_title' => '히든',
		'ip_address_pages' => 'ip 주소 페이지',
		'layout_title' => '레이아웃',
		'link_name' => '링크의 텍스트:',
		'link_new_window' => '새 창에서 링크 열기',
		'link_url' => '링크의 URL - 절대적이거나 상대적인 Q2A 루트 :',
		'lists_title' => '목록',
		'mailing_complete' => '메일링 완료',
		'mailing_explanation' => '유저는 자신의 계정 페이지에서 구독을 취소 할 수 있습니다.',
		'mailing_progress' => '^2 의 ^1 유저를 위한 메일링 완료됨 ...',
		'mailing_title' => '메일링',
		'mailing_unsubscribe' => '구독해지 링크는 모든 메시지의 하단에 추가됩니다.',
		'maintenance_admin_only' => '당신의 위치는 ^1메인^2 이고 일반 유저는 현재 액세스할 수 없습니다.',
		'maximum_x' => ' (최대 ^)',
		'approve_users_title' => '유저 허가',
		'module_x_database_init' => '^1 ^2 모듈은 ^3데이터베이스 초기화^4를 요구합니다.',
		'most_flagged_title' => '컨텐츠 신고',
		'mysql_version' => 'MySQL 버전:',
		'nav_links_explanation' => '네비게이션 링크 보기:',
		'nav_qa_is_home' => 'Q&A (홈페이지로 링크)',
		'neat_urls_note' => ' (^1htaccess^2 파일 필요)',
		'no_approve_found' => '컨텐츠가 승인을 기다리고 있지않습니다',
		'no_classification' => '없음',
		'no_flagged_found' => '컨텐츠 찾는것이 신고되지않음',
		'no_hidden_found' => '숨겨진 컨텐츠 찾는것이 없음',
		'no_image_gd' => '유저가 자신의 avatars를 직접 업로드 할 수 있도록 PHP의 설치 버전 , GD 이미지 지원없이 컴파일이 지원됨.',
		'no_link' => '링크 없음',
		'no_multibyte' => 'PHP의 설치 버전은 멀티 바이트 문자열의 지원없이 컴파일됨. 비 로마 문자의 검색은 덜 효과적 일 것입니다.',
		'no_privileges' => '오직 관리자만 이 페이지를 제어할 수 있을것입니다.',
		'no_unapproved_found' => '승인을 기다리는 유저 없음',
		'not_logged_in' => '이 페이지를 제어할려면 관리자로 ^1로그인^2해야 합니다.',
		'opposite_main_menu' => '상단에있는 탭의 맨 끝',
		'options_reset' => '리셋 옵션',
		'options_saved' => '옵션 저장',
		'options' => '옵션',
		'page_already_used' => '이 페이지는 이미 사용되고 있습니다.',
		'page_content_html' => '페이지에 표시할 내용 - HTML 허용:',
		'page_default_slug' => '페이지-^',
		'page_heading' => '페이지의 상단에 표시할 제목:',
		'page_name' => '페이지의 이름 (또한 탭이나 링크에 사용됨):',
		'page_slug' => '페이지 대용 (URL 조각):',
		'pages_explanation' => '\'페이지 추가\' 버튼을 클릭하면 Q2A 사이트에 사용자 지정 내용을 추가합니다, 또는 \'링크 추가\'는 모든 다른 웹페이지로 링크합니다.',
		'pages_title' => '페이지',
		'pause_mailing_button' => '메일링 중지',
		'per_ip_hour' => 'per IP/시간',
		'per_user_hour' => 'per 유저/시간',
		'permissions_title' => '권한',
		'permit_to_view' => '곧 쓸수 있는:',
		'php_version' => 'PHP 버전:',
		'pixels' => '픽셀',
		'plugin_module' => ' (플러그인 모듈: ^)',
		'plugin_pages_explanation' => '플러그인을 통해 사용할 수 페이지:',
		'plugins_title' => '플러그인',
		'points_defaults_shown' => '기본값은 다음과 같습니다 하지만 아직 적용하지않습니다:',
		'points_required' => '포인트는 제목을 받을 필요가 있습니다:',
		'points_title' => '포인트',
		'points' => '포인트',
		'position' => '위치:',
		'posting_title' => '포스팅',
		'profile_fields' => '사용자 페이지 또는 등록 양식에 추가 칸:',
		'q2a_build_date' => '빌드 시각:',
		'q2a_db_size' => '데이터베이스 사이즈:',
		'q2a_db_version' => 'Q2A 데이터베이스 버전:',
		'q2a_latest_version' => '최신 버전:',
		'q2a_version' => 'Question2Answer 버전:',
		'question_lists' => '질문 목록',
		'question_pages' => '질문 페이지',
		'recalc_categories_backpaths' => '^2 의 ^1 카테고리를 위한 URL 주소 재 계산...',
		'recalc_categories_complete' => '모든 카테고리가 성공적으로 다시 계산 했습니다.',
		'recalc_categories_note' => ' - 게시물 카테고리와 카테고리 카운트',
		'recalc_categories_recounting' => ' ^2 의 ^1 카테고리를 위한 질문을 열거...',
		'recalc_categories_updated' => '^2 게시물의 ^1재계산...',
		'recalc_categories' => '카테고리 재계산',
		'recalc_points_complete' => '모든 유저의 포인트가 성공적으로 재계산되었습니다.',
		'recalc_points_note' => ' - 유저 랭크와 포인트 표시 ',
		'recalc_points_recalced' => '^2 사용자 의 ^1 재 계산...',
		'recalc_points_usercount' => '유저의 총 인원수를 추정...',
		'recalc_points' => '유저 포인트 재계산',
		'recalc_posts_count' => '질문, 답변 과 의견의 총 수를 세기...',
		'recalc_stop' => '재계산 중지',
		'recent_approve_title' => '최근 승인을 위해 대기중인 컨텐츠',
		'recent_hidden_title' => '최근 숨겨진 컨텐츠',
		'recount_posts_as_recounted' => '답변을 다시 세고 ^2 의 ^1 게시물의 이슈를 식힘...',
		'recount_posts_complete' => '모든 게시물은 성공적으로 다시 수를 세었습니다.',
		'recount_posts_note' => ' - 답변과 투표의 수는, 각 게시물에 대한 인기가 없거나 신고됩니다.',
		'recount_posts_stop' => '다시 카운팅 중지',
		'recount_posts_votes_recounted' => '^2 게시물의 ^1 에 대한 투표 및 신고를 재계산...',
		'recount_posts' => '게시물 다시 셈',
		'refill_events_complete' => '모든 이벤트 스트림은 성공적 다시 채워졌습니다.',
		'refill_events_note' => ' - 유저마다\'의 업데이트 목록',
		'refill_events_refilled' => '^2 질문의 ^1은 다시 채워짐...',
		'refill_events' => '이벤트 스트림을 다시 채웁니다',
		'registration_fields' => '가입 칸을 추가',
		'reindex_content' => '컨텐츠 다시색인',
		'reindex_content_note' => ' - 검색과 관련된 질문에 대한 제안',
		'reindex_content_stop' => '다시색인 중지',
		'reindex_pages_reindexed' => '^2페이지의 ^1 다시 색인...',
		'reindex_posts_complete' => '모든 게시물은 성공적으로 다시 색인되었습니다.',
		'reindex_posts_reindexed' => '^2 포스트의 ^1 를 재색인...',
		'reindex_posts_wordcounted' => '^1 of ^2 단어의 ^1 다시셈...',
		'requires_php_version' => '비활성화 - 필요한 PHP ^ 이상',
		'requires_q2a_version' => '비활성화 - 필요한 Question2Answer ^ 이상',
		'reset_options_button' => '기본값으로 재설정',
		'reset_options_confirm' => '당신은 기본값으로 이 페이지의 모든 옵션을 다시 설정하시겠습니까 ?',
		'resume_mailing_button' => '메일링 다시시작',
		'save_options_button' => '옵션 저장',
		'save_recalc_button' => '저장하고 재계산',
		'save_view_button' => '저장하고 보기',
		'send_test_button' => '나에게 테스트 보내기',
		'show_defaults_button' => '기본 설정보기',
		'show_on_register_form' => '사용자 가입 양식에 칸 표시',
		'slug_bad_chars' => '슬러그 는 이러한 문자를 포함 할 수 없습니다: ^',
		'slug_reserved' => '이 슬러그은 다른 페이지 에서 사용하기 위해 예약되어 있습니다',
		'spam_title' => '스팸',
		'start_mailing_button' => '메일링 시작',
		'stats_title' => '통계',
		'stop_recalc_warning' => '데이터베이스 정리 작업이 실행 중입니다. 지금 이 페이지를 닫으면 작업이 중단됩니다 .',
		'tag_pages' => '테그 페이지',
		'tags_and_categories' => '태그와 카테고리',
		'tags_not_shown' => '몇 가지 질문의 태그가 표시되지 않습니다  .',
		'tags' => '태그',
		'test_sent_to_x' => '테스트 메시지는 ^ 보냈습니다',
		'title_already_used' => '이 값은 이미 다른 타이틀로 사용됨',
		'top_level_categories' => '최고 레벨의 카테고리:',
		'total_as' => '전체 답변:',
		'total_cs' => '전체 댓글:',
		'total_qs' => '전체 질문:',
		'unnamed_plugin' => '이름없는 플러그인',
		'upgrade_db' => '귀하의 Question2Answer 데이터베이스는 이 버전 으로 ^1 upgraded ^2 가 필요합니다.',
		'url_format_note' => '^ 레이블 옵션 은 귀하의 사이트에 대한 작업\' 구성. 최고의 검색 엔진 최적화 (SEO) 의 경우 , 사용할수 있는 최초의 ^ 옵션을 사용합니다.',
		'user_pages' => '유저 페이지',
		'user_title' => '유저 타이틀 - HTML 허용:',
		'user_titles' => '포인트를 기준으로한 유저 타이틀:',
		'users_active' => '활성화 유저:',
		'users_must_have' => '유저가 있어야 합니다',
		'users_posted' => '게시된 사용자:',
		'users_registered' => '가입한 유저:',
		'users_title' => '유저',
		'users_voted' => '투표 유저:',
		'version_get_x' => '^얻음',
		'version_requires_php' => '^1 필요 PHP ^2',
		'version_requires_q2a' => '^1 필요 Q2A ^2',
		'version_latest_unknown' => '알 수 없는 최신',
		'version_latest' => '최신',
		'viewing_title' => '보기',
		'widget_all_pages' => '사용할 수있는 모든 위젯 페이지에 이 위치 표시 ',
		'widget_global_options' => ' - ^1옵션^2',
		'widget_name' => '위젯의 이름:',
		'widget_no_positions' => '이 위젯은 이미 가능한 모든 위치에 추가되었습니다.',
		'widget_not_available' => '이 위젯은 사용할 수 없습니다. 위젯을 제공하는 플러그인이 이미 설치되어 있기 때문입니다.',
		'widget_pages_explanation' => '다음 페이지 에서 이 위치의 위젯보기:',
		'widgets_explanation' => '사용 가능한 위젯:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
