<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
	korea translation made by minwook shin
	https://github.com/minwook-shin
*/

	return array(
		'1_answer_title' => '1 답변',
		'a_convert_to_c_on' => '이 답변을 댓글로 변환:',
		'a_convert_to_c' => '이 답변을 댓글로 변환',
		'a_convert_warn_cs' => '주의: 이 변환은 되돌릴 수 없습니다 또한 이 응답 \' 의 코멘트를 이동합니다.',
		'a_convert_warn' => '주의: 이 변환은 반전 될 수 없습니다.',
		'a_notify_email' => '내 답변이 선택되거나 댓글이 생길 경우에는 이 주소로 이메일 보내기:',
		'a_notify_label' => '내 답변이 선택되거나 댓글이 생길 경우에는 이메일 보내기',
		'a_notify_x_label' => '내 답변이 선택 또는 댓글이 생길 경우 내 이메일(^ )로 보내기',
		'a_waiting_your_approval' => '이 답변은 당신의 허가를 기다리고 있습니다',
		'a_your_waiting_approval' => '당신의 답변은 확인하고 곧 승인 될 것입니다.',
		'add_answer_button' => '답변 추가',
		'add_comment_button' => '댓글 추가',
		'add_q_favorites' => '이 질문을 내 즐겨 찾기에 추가',
		'anon_name_label' => '보여지는 당신의 이름 (옵션):',
		'answer_button' => '답변',
		'answer_limit' => '너무 많은 답변을 함 - 몇시간후 다시 시도하십시오',
		'answer_must_be_approved' => '당신이 질문에 대답 하기 전에 계정이 승인을 받아야합니다.',
		'answer_must_confirm' => '^5이메일 주소 확인^6 질문에 대답 하십시오 .',
		'answer_must_login' => '질문에 대한 답변을 하려면 ^1로그인^2 또는 ^3가입^4해야합니다.',
		'answer_q_popup' => '이 질문에 답변',
		'approve_a_popup' => '이 답변에 허가',
		'approve_button' => '승인',
		'approve_c_popup' => '이 댓글에 허가',
		'approve_q_popup' => '이 질문에 허가',
		'ask_button' => '질문하기',
		'ask_follow_from_a' => '귀하의 질문이 답변과 관련이 있을 것입니다:',
		'ask_follow_title' => '관련 질문하기',
		'ask_limit' => '너무 많은 질문을 받음 - 몇시간후 다시 시도하십시오',
		'ask_must_be_approved' => '당신이 질문을 하기 전에 당신의 계정은 허가를 받아야합니다.',
		'ask_must_confirm' => '질문을 묻기전에 ^5이메일 주소 확인^6을 해주십시오.',
		'ask_must_login' => '질문을 묻기전에 ^1로그인^2 또는 ^3가입^4 해주십시오.',
		'ask_same_q' => '계속하기전에, 이미 요청 하지 않은 질문을 확인하십시오 :',
		'ask_title' => '질문 묻기',
		'c_notify_email' => '댓글이 내 뒤에 추가 되는 경우 이 주소로 이메일 보내기:',
		'c_notify_label' => '댓글이 내 뒤에 추가 되는 경우 이 주소로 이메일 보내기',
		'c_notify_x_label' => '댓글이 내 뒤에 추가 되는 경우 (^) 나에게 이메일 보내기',
		'c_waiting_your_approval' => '이 의견은 당신의 승인을 기다리고 있습니다',
		'c_your_waiting_approval' => '댓글이 확인하고 곧 승인될 것입니다.',
		'category_js_note' => '카테고리를 선택하려면, 웹 브라우저에서 자바 스크립트 (JavaScript)를 설치해주십시오 .',
		'category_required' => '카테고리를 선택해주십시오.',
		'category_ask_not_allowed' => '이 카테고리의 질문을 할 수 있는 권한이 없습니다',
		'claim_button' => '내가 씀',
		'claim_a_popup' => '유저 계정이 답변을 할당',
		'claim_c_popup' => '유저 계정이 댓글을 할당',
		'claim_q_popup' => '유저 계정이 질문을 할당',
		'clear_flags_button' => '신고 클리어',
		'clear_flags_popup' => '모든 유저에 대한 신고 삭제',
		'close_button' => '닫기',
		'close_duplicate_error' => '중복 질문을 찾을 수 없습니다 - 다른 질문 URL , 예를 들어보면 번호를 입력 해보십시오 (123) .',
		'close_duplicate' => '이 질문은 다른 질문과 중복됩니다.',
		'close_form_button' => '질문 닫기',
		'close_form_title' => '질문 닫기',
		'close_original_note' => '또한 URL로부터, 질문 번호를 입력 할 수 있습니다 예:(123) .',
		'close_original_title' => '원래 질문 의 URL:',
		'close_q_popup' => '새로운 답변이 질문을 닫습니다',
		'close_reason_title' => '이 질문을 닫는 이유:',
		'closed_as_duplicate' => '중복으로 폐쇄:',
		'closed_with_note' => '폐쇄 기록:',
		'comment_a_popup' => '이 답변에 댓글을 추가',
		'comment_button' => '댓글',
		'comment_limit' => '너무 많은 댓글을 받음 - 몇 시간후에 다시 시도하십시오',
		'comment_must_be_approved' => '당신은 댓글을 추가하기 전에 계정이 허가를 받아야합니다.',
		'comment_must_confirm' => '댓글을 추가하려면^5이메일 확인^6해주세요.',
		'comment_must_login' => '댓글을 추가하려면 ^1로그인^2 또는 ^3가입^4해주세요.',
		'comment_on_a' => '답변: ',
		'comment_on_q' => '질문: ',
		'comment_q_popup' => '이 질문에 댓글을 추가',
		'delete_a_popup' => '영구적 답변 삭제',
		'delete_button' => '삭제',
		'delete_c_popup' => '영구적 댓글 삭제',
		'delete_q_popup' => '영구적 질문 삭제',
		'duplicate_content' => '당신의 제출이 중복 된 것으로 보입니다.',
		'edit_a_popup' => '답변 수정',
		'edit_a_title' => '답변 수정',
		'edit_button' => '수정',
		'edit_c_popup' => '댓글 수정',
		'edit_c_title' => '댓글 수정',
		'edit_must_confirm' => '이것을 수정하려면 ^5이메일 확인^6해주세요.',
		'edit_must_login' => '이것을 수정하려면^1로그인^2 또는 ^3가입^4해주세요.',
		'edit_q_popup' => '질문 수정',
		'edit_q_title' => '질문 수정',
		'example_tags' => '태그 예시: ',
		'flag_a_popup' => '스팸 또는 부적절한 신고의 답변',
		'flag_button' => '신고',
		'flag_c_popup' => '스팸 또는 부적절한 신고의 댓글',
		'flag_hide_button' => '신고 하고 숨기기',
		'flag_limit' => '너무 많은 게시물 신고 - 몇시간후 다시 시도 해주십시오',
		'flag_must_confirm' => '게시물 신고 하려면^5이메일 주소 확인^6해주세요.',
		'flag_must_login' => '게시물 신고 하려면^1로그인^2 또는 ^3가입^4해주세요.',
		'flag_not_allowed' => '이것은 신고가 허용되지않습니다',
		'flag_q_popup' => '스팸 또는 부적절한 질문을 신고',
		'follow_a_popup' => '이 답변에 관한 새로운 질문',
		'follow_button' => '관련 질문 묻기',
		'follows_a' => '답변과 관련되는:',
		'follows_q' => '질문에 대한:',
		'hide_a_popup' => '답변 숨기기',
		'hide_button' => '숨기기',
		'hide_c_popup' => '댓글 숨기기',
		'hide_q_popup' => '질문 숨기기',
		'matching_tags' => '태그 일치: ',
		'max_tags_x' => '^ 태그의 최대 허용됨',
		'min_tags_x' => '적어도 ^ 태그 /s 를 제공 하십시오',
		'notify_email_note' => '개인정보 보호: 이메일 주소는 이 알림을 발송하기 위해 사용됩니다.',
		'q_category_label' => '카테고리:',
		'q_content_label' => '질문에 대한 더 많은 정보:',
		'q_hidden_author' => '이 질문은 글쓴이에 의해 숨겨져 있습니다',
		'q_hidden_flagged' => '이 질문은 신고 및 숨겨짐',
		'q_hidden_other' => '이 질문은 숨겨짐',
		'q_notify_email' => '내 질문에 답변 혹은 댓글이 달릴 경우 이 주소로 이메일을 보내기 :',
		'q_notify_label' => '내 질문에 대한 답변 이나 댓글이 달릴 경우 이메일을 보내기',
		'q_notify_x_label' => '내 질문에 대한 답변 이나 댓글이 달릴 경우 내 메일(^ )로 보내기',
		'q_tags_comma_label' => '태그 - 컴마(,)를 사용하여 분리하십시오:',
		'q_tags_label' => '태그 - 각 단어를 결합하려면 하이픈을 사용하십시오:',
		'q_title_label' => '한 문장의 질문:',
		'q_waiting_approval' => '이 질문의 허가을 기다리고 있습니다',
		'q_waiting_your_approval' => '이 질문은 당신의 허가를 기다리고 있습니다',
		'q_your_waiting_approval' => '귀하의 질문은 확인하고 곧 허가될 것입니다.',
		'recat_button' => '다시 분류',
		'recat_popup' => '질문\'의 카테고리 바꾸기',
		'recat_q_title' => '질문 재분류',
		'reject_a_popup' => '이 답변 거부',
		'reject_button' => '거부',
		'reject_c_popup' => '이 댓글 거부',
		'reject_q_popup' => '이 질문 거부',
		'remove_q_favorites' => '내 즐겨찾기로부터 질문 제거',
		'reopen_button' => '다시 열기',
		'reopen_q_popup' => '이 질문 다시 열기',
		'reply_button' => '리플',
		'reply_c_popup' => '댓글에 리플달기',
		'reshow_a_popup' => '이 답변 다시보기',
		'reshow_button' => '다시 보기',
		'reshow_c_popup' => '이 댓글 다시 보기',
		'reshow_q_popup' => '이 댓글 다시 보기',
		'retag_button' => '다시 태그',
		'retag_cat_popup' => '질문을 \'의 카테고리나 태그로 바꾸기',
		'retag_popup' => '질문을 \'의 태그로 바꾸기',
		'retag_q_title' => '질문 다시 태그',
		'save_silent_label' => '이 편집된 것을 숨기기 위해 자동으로 저장됨',
		'select_popup' => '우수 답변으로 선택합니다',
		'select_text' => '우수 답변',
		'show_1_comment' => '1 댓글 보기',
		'show_1_previous_comment' => '1 이전 댓글 보기',
		'show_x_comments' => '^ 댓글 보기',
		'show_x_previous_comments' => '^ 이전 댓글 보기',
		'unflag_button' => '신고 해제',
		'unflag_popup' => '당신의 추가 신고를 제거',
		'unselect_popup' => '선택 사항을 제거 합니다',
		'x_answers_title' => '^ 답변',
		'your_answer_title' => '당신의 답변',
		'your_comment_a' => '답변에 댓글:',
		'your_comment_q' => '질문에 댓글:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
