<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-options.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
	korea translation made by minwook shin
	https://github.com/minwook-shin
*/

	return array(
		'allow_change_usernames' => '게시물은 유저가 자신의 이름을 변경할 수 있도록 허용:',
		'allow_close_questions' => '허용 질문은 수동으로 폐쇄 함:',
		'allow_login_email_only' => '전용 이메일 주소로 로그인 (유저이름 아님):',
		'allow_multi_answers' => '유저마다 복수 응답 허용:',
		'allow_no_category' => '카테고리가 없는 질문 허용',
		'allow_no_sub_category' => '카테고리 있지만 하위 범주가 없는 질문 허용',
		'allow_private_messages' => '유저 간의 비공개 메시지를 사용:',
		'allow_user_walls' => '유저 프로필에 담벼락 게시물을 사용:',
		'allow_self_answer' => '사용자가 자신의 질문에 대답 할 수 있도록 허용 :',
		'allow_view_q_bots' => '검색 엔진이 질문 페이지를 볼 수 있도록 허용',
		'approve_user_required' => '모든 새로운 유저의 승인을 받아야함:',
		'avatar_allow_gravatar' => '^1Gravatar^2 아바타 허용:',
		'avatar_allow_upload' => '유저의 avatars 업로드를 허용:',
		'avatar_default_show' => '기존 avatar:',
		'avatar_message_list_size' => '메시지 목록의 아바타의 크기:',
		'avatar_profile_size' => '유저 프로필의 아바타 크기:',
		'avatar_q_list_size' => '질문 목록의 아바타 크기:',
		'avatar_q_page_a_size' => '대답의 아바타 크기:',
		'avatar_q_page_c_size' => '댓글의 아바타 크기:',
		'avatar_q_page_q_size' => '질문의 아바타 크기:',
		'avatar_store_size' => '아바타를 저장하는 최대 크기:',
		'avatar_users_size' => '최고 사용자 페이지 에 아바타 크기:',
		'block_bad_words' => '검열 단어 - 공백 또는 쉼표로 구분:',
		'block_ips_write' => '차단 된 IP 주소 - 공백 또는 쉼표 로 구분합니다 :',
		'captcha_module' => 'captcha 모듈 사용:',
		'captcha_on_anon_post' => '익명 게시물을 위한 captcha 사용:',
		'captcha_on_feedback' => '페이스북 양식에 captcha 사용:',
		'captcha_on_register' => '유저 가입을 위한 captcha 사용:',
		'captcha_on_reset_password' => '비밀번호 리셋 양식에 captcha 사용:',
		'captcha_on_unapproved' => '만약 유저가 허가 받지않았을때 captcha 사용:',
		'captcha_on_unconfirmed' => '만약 이메일이 확인되지않은 경우 captcha 사용:',
		'columns_tags' => '태그 페이지에 칼럼:',
		'columns_users' => '유저 페이지에 칼럼:',
		'comment_on_as' => '답변에 대한 댓글을 허용:',
		'comment_on_qs' => '질문에 대한 댓글을 허용:',
		'confirm_user_emails' => '유저 이메일의 확인을 요구:',
		'confirm_user_required' => '모든 새로운 사용자는 자신의 이메일을 확인:',
		'custom_home_content' => '홈페이지 컨텐츠 - HTML 확인됨:',
		'custom_home_heading' => '홈 페이지 제목:',
		'default_privacy' => '개인정보 보호: 귀하의 이메일 주소를 공유하거나 제 3 자에게 판매하지 않습니다 .',
		'default_sidebar' => '환영합니다 ^, 당신은 어디에서 질문을 하고 지역 사회의 다른 구성원으로부터 답변을 받을 수 있습니다.',
		'default_subject' => '^부터의 메시지',
		'default_suffix' => '질문&답변',
		'default_terms' => '나는^ 이용 약관 및 개인정보 보호정책에 동의',
		'do_ask_check_qs' => '질문 과 유사한 질문 ​​을 확인:',
		'do_close_on_select' => '선택한 답변의 질문을 닫기:',
		'do_complete_tags' => '입력하는 동안 태그와 일치하는 보기 :',
		'do_count_q_views' => '질문 뷰의 수를 계산합니다 :',
		'do_example_tags' => '질문을 기반으로 예를 든 태그를 표시:',
		'editor_for_as' => '답변에 대한 기본 편집기:',
		'editor_for_cs' => '덧글에 대한 기본 편집기 :',
		'editor_for_qs' => '질문에 대한 기본 편집기 :',
		'email_privacy' => '이메일 주소에 대한 개인 정보 보호 참고 - HTML 허용됨:',
		'extra_field_active' => '문의 폼에 추가 정보에 대한 사용자 정의 칸:',
		'extra_field_display_label' => '레이블이 질문 페이지에 추가 정보를 표시합니다 :',
		'extra_field_display' => '질문 페이지에 추가 정보를 표시',
		'feed_for_activity' => '최근 활동의 피드:',
		'feed_for_hot' => '이슈되는 질문의 피드:',
		'feed_for_qa' => '최근 질문과 답변의 피드:',
		'feed_for_questions' => '최근 질문의 피드:',
		'feed_for_search' => '검색결과의 피드:',
		'feed_for_tag_qs' => '각 태그에 대한 피드\'의 질문:',
		'feed_for_unanswered' => '대답없는 질문에 대한 피드:',
		'feed_full_text' => '피드의 전체 텍스트를 포함:',
		'feed_number_items' => '피드의 최대 길이:',
		'feed_per_category' => '카테고리 별 개별 피드:',
		'feedback_email' => '관리자 메시지에 대한 이메일 주소 - 유저를 보이지않음:',
		'feedback_enabled' => '피드백을 보내면 페이지를 제공합니다',
		'flagging_hide_after' => '자동으로 도착하는 게시물을 숨기기:',
		'flagging_notify_every' => '모두 추가 후 다시 이메일을 보내기:',
		'flagging_notify_first' => '게시물을 수신하는 경우 이메일을 보내기:',
		'flagging_of_posts' => '게시물 신고 할 수 있도록함:',
		'follow_on_as' => '질문에 대한 답변 관련 허용 :',
		'from_email' => '사이트에서 메시지의 보낸 사람 주소 :',
		'hot_weight_a_age' => '질문 새 응답이 있습니다:',
		'hot_weight_answers' => '질문 많은 답변이 있습니다:',
		'hot_weight_q_age' => '새로운 질문:',
		'hot_weight_views' => '많이 본 질문:',
		'hot_weight_votes' => '많은 up 투표를 받은 질문:',
		'links_in_new_window' => '새 윈도우에서 URLs링크 오픈:',
		'logo_height' => '로고 높이:',
		'logo_show' => '페이지 헤더에 있는 로고 이미지 보기',
		'logo_url' => '로고의 url - 절대 또는 Q2A 경로에 대해:',
		'logo_width' => '로고 폭:',
		'mailing_body' => '바디 텍스트:',
		'mailing_enabled' => '모든 유저에게 대량의 이메일 허용',
		'mailing_from_email' => '이메일 주소 에서:',
		'mailing_from_name' => '이름 에서:',
		'mailing_per_minute' => '최대 메일링 속도:',
		'mailing_subject' => '제목 줄:',
		'match_1' => '가장 좁은',
		'match_2' => '좁은',
		'match_3' => '기본',
		'match_4' => '넓은',
		'match_5' => '가장 넓은',
		'match_ask_check_qs' => '일치하는 유사 질문:',
		'match_example_tags' => '예시 태그와 일치:',
		'match_related_qs' => '일치하는 관련 질문:',
		'max_len_q_title' => '질문 제목의 최대 길이:',
		'max_num_q_tags' => '태그의 최대 수:',
		'max_rate_ip_as' => '답변을 추가하기 위한 속도 제한:',
		'max_rate_ip_cs' => '댓글을 게시 속도 제한:',
		'max_rate_ip_flags' => '신고 게시물에 대한 속도 제한:',
		'max_rate_ip_logins' => '로그인에 대한 속도 제한:',
		'max_rate_ip_messages' => '비밀과 담벼락 메시지에 대한 속도 제한:',
		'max_rate_ip_qs' => '질문 묻기에 대한 속도 제한:',
		'max_rate_ip_registers' => '유저 가입에 대한 속도 제한:',
		'max_rate_ip_uploads' => '파일 업로드에 대한 속도 제한:',
		'max_rate_ip_votes' => '투표에 대한 속도 제한:',
		'max_rate_user_as' => '유저의 시간 당 최대 답변:',
		'max_rate_user_cs' => '유저의 시간 당 최대 댓글:',
		'max_rate_user_flags' => '유저의 시간 당 최대 신고:',
		'max_rate_user_messages' => '유저의 시간 당 최대 비밀메시지:',
		'max_rate_user_qs' => '유저의 시간 당 최대 질문:',
		'max_rate_user_uploads' => '유저의 시간 당 최대 업로드:',
		'max_rate_user_votes' => '유저의 시간 당 최대 투표:',
		'min_len_a_content' => '답변의 최소 길이:',
		'min_len_c_content' => '댓글의 최소 길이:',
		'min_len_q_content' => '질문 내용의 최소 길이:',
		'min_len_q_title' => '질문 제목의 최소 길이:',
		'min_num_q_tags' => '태그의 최소 숫자:',
		'moderate_anon_post' => '익명의 게시물에 대해 중재를 사용:',
		'moderate_by_points' => '몇 가지 포인트 와 사용자에 대해 중재 를 사용:',
		'moderate_edited_again' => '다시 적당한 게시물 편집 후:',
		'moderate_notify_admin' => '게시물이 중재를 필요로 할 때 나에게 이메일 보내기:',
		'moderate_points_limit' => '보다 적은 비용으로 사용자에 대해 중재를 사용:',
		'moderate_unapproved' => '사용자가 아직 승인 하지 않을 경우 중재를 사용:',
		'moderate_unconfirmed' => '이메일을 확인 하지 않을 경우 중재를 사용:',
		'moderate_update_time' => '검토 게시물에 시간 표시 합니다 :',
		'moderate_users' => '사용자 의 검토 ( 승인 )를 사용 :',
		'neat_urls' => 'URL 구조:',
		'notify_admin_q_post' => '질문이 게시될 때 이 주소를 이메일로',
		'notify_users_default' => '기본적으로 전자 메일 알림 확인란을 선택합니다 :',
		'option_default' => '기본',
		'page_size_activity' => '모든 활동 페이지 의 길이:',
		'page_size_ask_check_qs' => '최대 비슷한 질문 보이기',
		'page_size_ask_tags' => '최대 태그 힌트 보이기:',
		'page_size_home' => 'Q&A 페이지의 길이:',
		'page_size_hot_qs' => '이슈! 페이지의 길이:',
		'page_size_pms' => '페이지 당 비밀 메시지:',
		'page_size_q_as' => '페이지 당 최대 답변:',
		'page_size_qs' => '질문 페이지의 길이:',
		'page_size_related_qs' => '최대 관련 질문:',
		'page_size_search' => '페이지 당 검색 결과:',
		'page_size_tag_qs' => '각 태그 페이지 에 대한 문의:',
		'page_size_tags' => '태그 페이지의 길이:',
		'page_size_una_qs' => '답변 없는 페이지의 길이:',
		'page_size_users' => '유저 페이지의 길이:',
		'page_size_wall' => '페이지당 담벼락 페이지:',
		'pages_prev_next' => '이전 / 다음 페이지로의 링크:',
		'permit_admins' => '어드민',
		'permit_all' => '모두',
		'permit_approve_users' => '등록 된 유저를 승인:',
		'permit_approved' => '유저만 승인',
		'permit_approved_points' => '충분한 포인트의 승인 사용자',
		'permit_block' => '유저나 ip의 차단또는 헤제:',
		'permit_confirmed' => '이메일 확인된 가입 유저',
		'permit_create_admins' => '어드민 생성:',
		'permit_create_eds_mods' => '에디터와 모더레이터 생성:',
		'permit_create_experts' => '전문가 생성:',
		'permit_delete_users' => '유저 삭제:',
		'permit_editors' => '에디터, 모더레이터, 어드민',
		'permit_experts' => '전문가, 에디터, 모더레이터, 어드민',
		'permit_moderators' => '모더레이터나 어드민',
		'permit_points_confirmed' => '가입 & 이메일 확인 & 충분한 포인트',
		'permit_points' => '충분한 포인트의 가입 유저',
		'permit_see_emails' => '유저 이메일 주소 보기:',
		'permit_supers' => '슈퍼 어드민',
		'permit_users' => '가입된 유저',
		'place_full_below_content' => '전체 폭 - 콘텐츠 아래',
		'place_full_below_footer' => '전체 폭 - 바닥 글 아래',
		'place_full_below_nav' => '전체 폭 - 탐색 아래',
		'place_full_top' => '전체 폭 - 맨 위로',
		'place_main_below_lists' => '주 영역 - 목록 아래',
		'place_main_below_title' => '주 영역 - 제목 아래',
		'place_main_bottom' => '주 영역 - 바닥',
		'place_main_top' => '주 영역 - 위',
		'place_side_below_categories' => '사이드 패널 - 카테고리 아래',
		'place_side_below_sidebar' => '사이드 패널 - 사이드 바 상자 아래',
		'place_side_last' => '사이드 패널 - 마지막',
		'place_side_top' => '사이드 패널 - 위',
		'points_a_selected' => '최고로 답을 선택한 것',
		'points_a_voted_max_gain' => '각각의 답변에 투표 부터 제한 :',
		'points_a_voted_max_loss' => '각각의 답변에 아래 표에서 제한 :',
		'points_base' => '모든 유저를 추가:',
		'points_multiple' => '모든 포인트 곱하기:',
		'points_per_a_voted_down' => 'down투표 당 답변:',
		'points_per_a_voted_up' => 'up투표 당 답변:',
		'points_per_q_voted_down' => 'down투표 당 질문:',
		'points_per_q_voted_up' => 'up투표 당 질문:',
		'points_post_a' => '답변 게시:',
		'points_post_q' => '질문 게시:',
		'points_q_voted_max_gain' => '각 질문 에 투표 부터 제한:',
		'points_q_voted_max_loss' => '각 질문 에 아래 표 에서 제한:',
		'points_select_a' => '귀하의 질문에 대한 답을 선택:',
		'points_vote_down_a' => '답변에 down 투표:',
		'points_vote_down_q' => '질문에 down 투표:',
		'points_vote_up_a' => '답변에 up 투표:',
		'points_vote_up_q' => '질문에 up 투표:',
		'q_urls_remove_accents' => '질문 URL의 악센트 를 제거:',
		'q_urls_title_length' => 'URL 에서 질문 제목 길이:',
		'register_notify_admin' => '새로운 유저가 등록 할 때 이메일을 보내기:',
		'search_module' => '검색 모듈 사용:',
		'show_a_form_immediate' => '즉시 대답 양식을 표시:',
		'show_always' => '항상',
		'show_c_reply_buttons' => '댓글에 회신 버튼을 표시:',
		'show_custom_answer' => '답변 양식에 커스텀 메시지 - HTML 허용됨:',
		'show_custom_ask' => '질문 양식에 커스텀 메시지 - HTML 허용됨:',
		'show_custom_comment' => '댓글 양식에 커스텀 메시지 - HTML 허용됨:',
		'show_custom_footer' => '모든 페이지의 하단에 커스텀 HTML:',
		'show_custom_header' => '모든 페이지의 상단에 있는 커스텀 HTML:',
		'show_custom_home' => '대신 Q & A 의 홈 페이지에서 커스텀 내용',
		'show_custom_in_head' => '사용자 정의 HTML의 <head> 모든 페이지 의 섹션 :',
		'show_custom_register' => '가입양식에 커스텀 메시지 - HTML 허용됨:',
		'show_custom_sidebar' => '모든 페이지의 사이드 바 상자에 커스텀 HTML:',
		'show_custom_sidepanel' => '모든 페이지의 사이드 패널 상자에 커스텀 HTML:',
		'show_custom_welcome' => '이메일의 커스텀 메시지는 새로운 등록 된 사용자에게 전송 :',
		'show_post_update_meta' => '포스트 메타의 수정/업데이트 보기:',
		'show_fewer_cs_count' => '부분적으로 숨겨진 경우 , 가장 최근의 표시:',
		'show_fewer_cs_from' => '보다 더 많은 경우, 부분적으로 의견을 숨기기:',
		'show_full_date_days' => '후 전체 날짜를 표시:',
		'show_home_description' => '홈페이지를 위한 <meta> 설명 포함:',
		'show_if_no_as' => '만약 답변이 없다면',
		'show_message_history' => '비밀 메시지 기록 보관과 보기:',
		'show_never' => '절대',
		'show_notice_visitor' => '처음 방문자를 위한 상단 공지 사항 - HTML 허용됨:',
		'show_notice_welcome' => '새로운 등록된 사용자를 위한 상단 공지 사항 - HTML 허용됨:',
		'show_register_terms' => '등록 양식 에 대한 이용 약관은 체크 박스 - HTML 허용됨:',
		'show_selected_first' => '정상에 선택한 답변 이동:',
		'show_url_links' => '게시물안의 URL을 탐지하고 링크:',
		'show_user_points' => '유저 이름 옆에 포인트 표시:',
		'show_user_titles' => '유저 이름 옆에 제목을 표시:',
		'show_view_counts' => '질문 목록의 보기 수를 표시:',
		'show_view_count_q_page' => '질문 페이지 뷰 수를 표시:',
		'show_when_created' => '유저 게시물의 나이를 표시:',
		'site_language' => '사이트 언어:',
		'site_maintenance' => '임시 유지 보수를 위해 사이트를 다운',
		'site_text_direction' => '사이트 텍스트 디렉션:',
		'site_theme' => '사이트 테마:',
		'site_theme_mobile' => '모바일의 테마:',
		'site_title' => 'Q&A 사이트 이름:',
		'site_url' => '선호하는 사이트 URL:',
		'smtp_active' => '대신 로컬 메일 의 SMTP를 통해 이메일 보내기',
		'smtp_address' => 'SMTP 서버 주소:',
		'smtp_authenticate' => 'SMTP 유저 이름 과 암호를 보내기',
		'smtp_password' => 'SMTP 비밀번호:',
		'smtp_port' => 'SMTP 서버 포트:',
		'smtp_secure_none' => '없음',
		'smtp_secure' => 'SMTP 보안 연결:',
		'smtp_username' => 'SMTP 유저이름:',
		'sort_answers_by' => '답변을 기준으로 정렬:',
		'sort_time' => '시간',
		'sort_votes' => '투표',
		'suspend_register_users' => '일시적으로 새로운 사용자 등록을 중단 :',
		'tag_separator_comma' => '유일한 태그 구분 기호로 쉼표를 사용 :',
		'tags_or_categories' => '질문 분류 :',
		'time_approved' => '허가한 시간',
		'time_written' => '쓴 시간',
		'votes_separated' => '별도의 up 및 down 투표 보기:',
		'voting_on_as' => '답변에 투표 허용:',
		'voting_on_q_page_only' => '질문 페이지에서만 투표 허용:',
		'voting_on_qs' => '질문에 투표 허용:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
